work_dir: ./work_dir/label

# feeder
feeder: feeder.Feeder_label
train_feeder_args:
  data_path: ./data/fft_data/train/data.npy
  label_path: ./data/fft_data/train/label.npy
  modal: 0
test_feeder_args:
  data_path: ./data/fft_data/valid/data.npy
  label_path: ./data/fft_data/valid/label.npy
  modal: 0

# model
model: net.CNN
model_args:
  channels: 9
  num_classes: 8

#optim
optimizer: 'Adam'
weight_decay: 1e-5
base_lr: 1e-4
step: [10, 50]

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 80
nesterov: True



